### ISSUE TITLE
Can't build image from Dockerfile

### ISSUE THREAD

**Issue by oilbeater** [Dataman-Cloud/OpenDockerFile#3]
```
Sending build context to Docker daemon 17.92 kB
Step 0 : FROM centos7/jdk8
Pulling repository docker.io/centos7/jdk8
Error: image centos7/jdk8:latest not found
```

The image centos7/jdk8 can not be found.

There are still some defect in the Dockerfile. You can turn to a [Dockerfile lint tool](http://dockerfile-linter.com/) for more advices.

**Comment by ss75710541** [comment]
docker pull testregistry.dataman.io/centos7/jdk8:2015120701

**Comment by ss75710541** [comment]
jdk8 的 dockerfile 已经添加到 https://github.com/Dataman-Cloud/OpenDockerFile/tree/master/centos7-jdk8
